### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by adipose** [ShiftMediaProject/fribidi#2]
When using this project, I detected a memory leak.  By defining USE_SIMPLE_MALLOC (which avoids the custom memory allocator), the leak goes away.  I do note that this customer allocator was removed from the GNU project in this commit:

https://github.com/fribidi/fribidi/commit/3519ef07cf2b8610c30b22611466df0de2f74b19

**Comment by Sibras** [comment]
Project is now at 1.0.9. Check if the leak still exists now.

**Comment by adipose** [comment]
Seems good!
